### ISSUE TITLE
Encrypt files based on their filename

### ISSUE THREAD

**Issue by commjoen** [OWASP/wrongsecrets#975]
### Context

-   What should the challenge scenario be like?
There are 2 scenarios:
- [x] 1st contextual encryption mistake:There should be a file with a secret inside of the file, which is encrypted with the filename as a key.
- [ ] Second contextual encryption mistake: have the key next to the secret: use a json structure with 

```json
{"key":"<hardcoded key>",
    "secret":"<encrypted secret>"
} 
```

-   What should the participant learn from completing the challenge?
The key should not be with the secret or based on the content of the secret carrier.  We have seen multiple scenarios where known values such as the username owning the content and/or the contents of the file itself were used to encrypt a secret, which allows an attacker to find the key and decrypt the materials
-   For what category would the challenge be? (e.g. Docker, K8s, binary)
Docker

### Did you encounter this in real life? Could you tell us more about the scenario?
- Filename as encryption keys: multiple times
- Keys stored as part of the encrypted content: multiple times

## TODOs for this challenge:
- [x] Create a file `secrchallenge.md` that contains a base64 encoded AES encrypted secret which is the answer to the challenge. The AES key you need to use is `secrchallenge.md` (which is 16 characters ;-) ). make sure this file is in the [resources/executables](https://github.com/OWASP/wrongsecrets/tree/master/src/main/resources/executables) folder.
- [x] Implement the challenge around this file as described in contributing.md: the challenge should have the key hardcoded, and only read the secret from the file you just created (secrchallenge.md).
- [ ] Create a json file which follows the definition above and put it in the [resources/executables](https://github.com/OWASP/wrongsecrets/tree/master/src/main/resources/executables) folder
- [ ] Implement the challenge around this file as described in contributing.md: the challenge should read the key from the json file, and read the secret from the json file as well.

**Comment by adarsh-a-tw** [comment]
@commjoen Would like to pick this up. Can you please assign it to me?

**Comment by commjoen** [comment]
Hi @adarsh-a-tw ! Welcome  to the team! The issue is yours ;-).

Please be aware if you want to make this issue count for the hacktoberfest that the PR resolving this issue must be accepted/merged before the end of this month.

Have a look at https://github.com/OWASP/wrongsecrets/blob/master/CONTRIBUTING.md and https://github.com/OWASP/wrongsecrets/blob/master/README.md to get started.
If you need any other help: feel free to contact us over slack ;-).

**Comment by commjoen** [comment]
Pssst: you can make 2 hacktoberfest points by creating an MR per challenge ;-) (so 1 for the filename and 1 for the json file with the key next to the content ;-) )

**Comment by commjoen** [comment]
1 down, 1 to go :D , awesome work! & I am looking forward to your next one ;-)
